name: ecommerce_with_php
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  # DateTime
  jiffy: ^5.0.0
  intl: ^0.17.0
  http: ^0.13.4
  # Images
  cached_network_image: ^3.2.0 
  image_picker: ^0.8.7
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  # Google Map
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.5
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  # Firebase And Notification 
  firebase_messaging: ^14.3.0
  firebase_core: ^2.8.0
  flutter_local_notifications: ^14.0.0-dev.2
  cloud_firestore: ^4.4.5
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode 
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.1.2
  dropdown_search: ^5.0.6
  badges: ^3.0.2
  # Icon 
  # flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  # Google Auth
  google_sign_in: ^6.0.2  
  device_preview: ^1.1.0
  responsive_builder: ^0.6.4
  image_pickers: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
